// consts defined in `server/consts.go` generated by `build.mjs`
// do not edit manually.
export const VERSION = 127;
export const STABLE_VERSION = 118;
export const stableBuild = new Set(["preact","react","solid-js","svelte","vue"]);
export const assetsExts = new Set(["wasm","css","less","sass","scss","stylus","styl","json","jsonc","csv","xml","plist","tmLanguage","tmTheme","yml","yaml","pdf","txt","glsl","frag","vert","md","mdx","markdown","html","htm","vue","svelte","svg","png","jpg","jpeg","webp","gif","ico","eot","ttf","otf","woff","woff2","m4a","mp3","m3a","ogg","oga","wav","weba","mp4","m4v","ogv","webm","zip","gz","tar","tgz"]);
export const cssPackages = {"@unocss/reset":"tailwind.css","inter-ui":"inter.css","normalize.css":"normalize.css","modern-normalize":"modern-normalize.css","reset-css":"reset.css"};
export const fixedPkgVersions = {"@types/react@17":"17.0.59","@types/react@18":"18.2.6","isomorphic-ws@4":"5.0.0","resolve@1.22":"1.22.2"};
