// generated by `build.mjs`, do not edit manually.
export const VERSION = 135;
export const assetsExts = new Set(["wasm","css","less","sass","scss","stylus","styl","json","jsonc","csv","xml","plist","tmLanguage","tmTheme","yml","yaml","pdf","txt","glsl","frag","vert","md","mdx","markdown","html","htm","vue","svelte","svg","png","jpg","jpeg","webp","gif","ico","eot","ttf","otf","woff","woff2","m4a","mp3","m3a","ogg","oga","wav","weba","mp4","m4v","ogv","webm","zip","gz","tar","tgz"]);
export const cssPackages = {"@unocss/reset":"tailwind.css","inter-ui":"inter.css","normalize.css":"normalize.css","modern-normalize":"modern-normalize.css","reset-css":"reset.css"};
