// generated by `build.mjs`, do not edit manually.
export const VERSION = 136;
export const assetsExts = new Set(["node","wasm","less","sass","scss","stylus","styl","json","jsonc","csv","xml","plist","tmLanguage","tmTheme","yml","yaml","txt","glsl","frag","vert","md","mdx","markdown","html","htm","svg","png","jpg","jpeg","webp","gif","ico","eot","ttf","otf","woff","woff2","m4a","mp3","m3a","ogg","oga","wav","weba","gz","tgz"]);
export const cssPackages = {"@unocss/reset":"tailwind.css","inter-ui":"inter.css","normalize.css":"normalize.css","modern-normalize":"modern-normalize.css","reset-css":"reset.css"};
